# Generated by Django 5.0.3 on 2024-12-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('last_transaction_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('average_price', models.FloatField(blank=True, null=True)),
                ('trading_volume_best', models.FloatField(blank=True, null=True)),
                ('total_trading_volume', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
